# Generated by Django 4.1 on 2023-07-31 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pspuser',
            name='bio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RemoveField(
            model_name='pspuser',
            name='following',
        ),
        migrations.AddField(
            model_name='pspuser',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
